version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: vaccination_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
